In [1]:
import numpy as np

In [4]:
def analyze(res):
    # output properties of data
    print("Mean:")
    print(np.mean(res, axis=0))
    print("Std:")
    print(np.std(res, axis=0))
    
    # take the average of the results
    res = np.mean(res, axis=0)
    
    # map values to the range [0, 1]
    res = np.interp(res, [np.min(res), np.max(res)], [0, 1])
    
    # print results
    print("Matrix Game Social Dilemma:")
    print(res)
    
    return res

In [2]:
results  = np.load('raw/wolfpack_reduction/run_test.npy')
print(results.shape)
# print(res)

(5, 30, 3, 2, 2)


In [6]:
res1 = analyze(results[0,:,:,0])

Mean:
[[-2838.03333333 -2766.63333333]
 [-1522.23333333   136.96666667]
 [  460.8          505.        ]]
Std:
[[ 814.99408928  958.05123326]
 [ 537.26478161  473.60901479]
 [ 321.94620669  350.86977641]]
Matrix Game Social Dilemma:
[[ 0.          0.02135785]
 [ 0.39359464  0.88991036]
 [ 0.98677847  1.        ]]


In [7]:
res2 = analyze(results[1,:,:,0])

Mean:
[[-2679.63333333 -2570.83333333]
 [-1279.26666667   300.03333333]
 [  518.43333333   501.43333333]]
Std:
[[ 648.19922263  601.19365063]
 [ 583.41574275  729.54124779]
 [ 490.64717013  473.91558203]]
Matrix Game Social Dilemma:
[[ 0.          0.03402055]
 [ 0.43787914  0.93170874]
 [ 1.          0.99468429]]


In [8]:
res3 = analyze(results[2,:,:,0])

Mean:
[[-2757.06666667 -2746.86666667]
 [-1520.46666667   133.63333333]
 [  478.73333333   502.53333333]]
Std:
[[ 634.26329619  624.42489451]
 [ 533.06151823  551.05054114]
 [ 464.83258157  534.46307845]]
Matrix Game Social Dilemma:
[[ 0.          0.00312922]
 [ 0.3793717   0.8868266 ]
 [ 0.99269849  1.        ]]


In [9]:
res4 = analyze(results[3,:,:,0])

Mean:
[[-2530.93333333 -2546.23333333]
 [-1345.66666667    85.73333333]
 [  432.43333333   474.93333333]]
Std:
[[ 619.43995853  634.89645788]
 [ 705.08190226  613.02060506]
 [ 508.29943166  382.35706988]]
Matrix Game Social Dilemma:
[[ 0.00506427  0.        ]
 [ 0.39738512  0.87117559]
 [ 0.98593259  1.        ]]


In [11]:
res5 = analyze(results[4,:,:,0])

Mean:
[[-2502.3        -2470.        ]
 [-1336.63333333   152.56666667]
 [  483.76666667   570.46666667]]
Std:
[[ 758.83666007  757.51228813]
 [ 638.93069438  685.37268126]
 [ 519.01969669  469.43829792]]
Matrix Game Social Dilemma:
[[ 0.          0.0105117 ]
 [ 0.37935411  0.86399879]
 [ 0.97178439  1.        ]]


In [12]:
np.round_(res5, decimals=2)

array([[ 0.  ,  0.01],
       [ 0.38,  0.86],
       [ 0.97,  1.  ]])