In [1]:
import numpy as np

In [3]:
results  = np.load('raw/wolfpack_reduction/run_test.npy')
print(results.shape)
# print(res)

(5, 60, 3, 2)


In [10]:
def analyze(res):
    # output properties of data
    print("Mean:")
    print(np.mean(res, axis=0))
    print("Std:")
    print(np.std(res, axis=0))
    
    # take the average of the results
    res = np.mean(res, axis=0)
    
    # map values to the range [0, 1]
    res = np.interp(res, [np.min(res), np.max(res)], [0, 1])
    
    # print results
    print("Matrix Game Social Dilemma:")
    print(res)
    
    return res

In [17]:
res1 = analyze(results[0])

Mean:
[[-2809.65       -2777.35      ]
 [-1459.28333333    79.21666667]
 [  535.78333333   669.23333333]]
Std:
[[ 850.14214155  789.13393086]
 [ 476.7649348   527.69799102]
 [ 431.25994063  450.56454834]]
Matrix Game Social Dilemma:
[[ 0.          0.00928459]
 [ 0.38816095  0.83040056]
 [ 0.96163999  1.        ]]


In [18]:
res2 = analyze(results[1])

Mean:
[[-2901.81666667 -2859.31666667]
 [-1537.05          76.25      ]
 [  482.06666667   483.76666667]]
Std:
[[ 767.06154668  779.35882818]
 [ 463.97655921  546.88160282]
 [ 437.42217848  464.34485628]]
Matrix Game Social Dilemma:
[[ 0.          0.01255323]
 [ 0.40311123  0.87963177]
 [ 0.99949787  1.        ]]


In [19]:
res3 = analyze(results[2])

Mean:
[[-2663.   -2720.8 ]
 [-1549.65    21.15]
 [  382.1    452.65]]
Std:
[[ 796.87129868  811.17792541]
 [ 636.07153227  629.93221395]
 [ 470.18488208  525.14965565]]
Matrix Game Social Dilemma:
[[ 0.01821362  0.        ]
 [ 0.36904631  0.86402811]
 [ 0.97776867  1.        ]]


In [20]:
res4 = analyze(results[3])

Mean:
[[-2894.81666667 -2854.01666667]
 [-1406.85         141.85      ]
 [  564.66666667   528.96666667]]
Std:
[[ 764.68055404  759.13816247]
 [ 554.02989766  611.35981836]
 [ 487.12560552  472.05769304]]
Matrix Game Social Dilemma:
[[ 0.          0.01179367]
 [ 0.4301124   0.8777804 ]
 [ 1.          0.98968054]]


In [21]:
res5 = analyze(results[4])

Mean:
[[-2824.75       -2862.15      ]
 [-1510.21666667   103.08333333]
 [  389.78333333   418.68333333]]
Std:
[[ 769.87727648  742.89364032]
 [ 492.25765921  633.76479054]
 [ 535.55031173  516.19778159]]
Matrix Game Social Dilemma:
[[ 0.01139954  0.        ]
 [ 0.4120701   0.90380493]
 [ 0.99119126  1.        ]]


In [23]:
np.round_(res5, decimals=2)

array([[ 0.01,  0.  ],
       [ 0.41,  0.9 ],
       [ 0.99,  1.  ]])